/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ProductsProductSlugRouteImport } from './routes/products/$productSlug';
import { Route as ProductsProductSlugEditRouteImport } from './routes/products/$productSlug_.edit';
import { Route as ProductsNewRouteImport } from './routes/products/new';
import { Route as SignInRouteImport } from './routes/sign-in';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsProductSlugEditRoute = ProductsProductSlugEditRouteImport.update({
  id: '/products/$productSlug_/edit',
  path: '/products/$productSlug/edit',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/sign-in': typeof SignInRoute;
  '/products/$productSlug': typeof ProductsProductSlugRoute;
  '/products/new': typeof ProductsNewRoute;
  '/products/$productSlug/edit': typeof ProductsProductSlugEditRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/sign-in': typeof SignInRoute;
  '/products/$productSlug': typeof ProductsProductSlugRoute;
  '/products/new': typeof ProductsNewRoute;
  '/products/$productSlug/edit': typeof ProductsProductSlugEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/sign-in': typeof SignInRoute;
  '/products/$productSlug': typeof ProductsProductSlugRoute;
  '/products/new': typeof ProductsNewRoute;
  '/products/$productSlug_/edit': typeof ProductsProductSlugEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/sign-in'
    | '/products/$productSlug'
    | '/products/new'
    | '/products/$productSlug/edit';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/sign-in' | '/products/$productSlug' | '/products/new' | '/products/$productSlug/edit';
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/products/$productSlug'
    | '/products/new'
    | '/products/$productSlug_/edit';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SignInRoute: typeof SignInRoute;
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute;
  ProductsNewRoute: typeof ProductsNewRoute;
  ProductsProductSlugEditRoute: typeof ProductsProductSlugEditRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/sign-in': {
      id: '/sign-in';
      path: '/sign-in';
      fullPath: '/sign-in';
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/products/$productSlug': {
      id: '/products/$productSlug';
      path: '/products/$productSlug';
      fullPath: '/products/$productSlug';
      preLoaderRoute: typeof ProductsProductSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/products/new': {
      id: '/products/new';
      path: '/products/new';
      fullPath: '/products/new';
      preLoaderRoute: typeof ProductsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/products/$productSlug_/edit': {
      id: '/products/$productSlug_/edit';
      path: '/products/$productSlug/edit';
      fullPath: '/products/$productSlug/edit';
      preLoaderRoute: typeof ProductsProductSlugEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
  ProductsNewRoute: ProductsNewRoute,
  ProductsProductSlugEditRoute: ProductsProductSlugEditRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
