// Public barrel — the module's entire public contract (ADR-0003: one barrel, no nested barrels).
export { RATING_RECOMPUTE_OP, REVIEWS_OUTBOX } from './outbox.js';
export {
  type CreateProductInput,
  createProduct,
  deriveProductSlug,
  getProductBySlug,
  type ListProductsInput,
  listProducts,
  type ProductDetailRecord,
  type ProductListPage,
  type ProductListSort,
  type ProductRatingSummary,
  type ProductRecord,
  type ProductSummaryRecord,
  type UpdateProductInput,
  updateProduct,
} from './products.js';
export {
  type ProductRatingRecord,
  RATING_LAG_INSTRUMENT,
  RATING_RECOMPUTE_INSTRUMENT,
  RATING_RECOMPUTE_OUTCOME,
  type RatingRecomputeOutcome,
  type RebuildProductRatingOptions,
  type RebuildProductRatingReport,
  type RecomputeProductRatingOptions,
  rebuildProductRating,
  recomputeProductRating,
} from './rating.js';
export {
  type ListReviewsForProductInput,
  listReviewsForProduct,
  type RemoveReviewInput,
  type ReviewListItem,
  type ReviewListPage,
  type ReviewMutationRecord,
  type ReviewRecord,
  removeReview,
  type SubmitReviewInput,
  type SubmitReviewResult,
  submitReview,
  type UpdateReviewInput,
  updateReview,
} from './reviews.js';
