import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

/**
 * The SPA build.
 *
 * Deliberately NOT using `@tanstack/router-plugin`: the route tree is a COMMITTED artifact
 * regenerated by `moon run app:route-tree` and verified by `app:route-tree-check`, so exactly one
 * generator produces it and CI can diff the result. A build-time plugin that silently regenerates
 * the file would make the freshness check a check of the build's own output rather than of what
 * is in git.
 *
 * `envDir` points at the repo root so the SPA reads the SAME `.env` the api does — that file is
 * the one `.env.example` documents, and two env files for one `bun run dev` session is how a
 * mismatched `VITE_API_URL` happens.
 */
export default defineConfig({
  plugins: [react(), tailwindcss()],
  envDir: '../..',
  server: {
    port: 5173,
  },
  preview: {
    port: 4173,
  },
  build: {
    // Sourcemaps ship: the error reports `shared/observability` forwards are worthless against
    // minified frames, and this is a first-party bundle, not a secret.
    //
    // Known, harmless build warning: `[SOURCEMAP_BROKEN] … @tailwindcss/vite:generate:build`. The
    // Tailwind plugin generates CSS without emitting a sourcemap for that transform. It concerns
    // the stylesheet only — the JS map is produced normally — and there is no plugin option to
    // silence it at the pinned version. Recorded so the next person does not chase it.
    sourcemap: true,
  },
});
